### ISSUE TITLE
Question in Section 7.2 about the selection of optimal assortment

### ISSUE THREAD

**Issue by coffezhou** [iosband/ts_tutorial#3]
Hi,
I read the tutorial, which is the best material of Thompson Sampling. Thanks!
In Section 7.2, I read the source code and I found there is a function find_optimal_assortment() that is used to generate all possible assortments and select the optimal optimal assortment for a given  sampled parameter. However, if we have many products (e.g., 100) such that we cannot enumerate all assortments, then in this case how can we choose the assortment according to the sampled parameter?

**Comment by iosband** [comment]
Hi CoffeZhou!

Very sorry for the delay here.
You raise a good question and this code would not be able to handle that problem.

Probably, you would be forced to use some approximate solution method given a single *known* parameter.
For example, you might have some greedy heuristic that picks items iteratively!

However, this type of question (solution given a *known* parameter) is not the focus on Thompson sampling tutorial so we did not go in to too much detail here.
